services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: nodejs-dev-docker-image:latest
        container_name: portfolio-nodejs-container
        volumes:
            - .:/app
        ports:
            - "3000:3000"
        tty: true